### ISSUE TITLE
Bad state: No record groups have been started

### ISSUE THREAD

**Issue by sterrenb** [alexZaicev/dart-coco#1]
Hi, when trying to generate a coverage report, I encounter the following error.

I am using version `1.0.4`. Coverage data is saved in the default directory (`./coverage/`).

```shell
C:\project>flutter pub run dart_coco --verbose --html
2020-04-23 11:24:55.529  --- [INFO] --- [Dart-CoCo] --- Cleaning report direcotry
2020-04-23 11:24:55.735  --- [ERROR] --- [Dart-CoCo] --- Dart-CoCo reporter encountered an unexpeced error..
2020-04-23 11:24:55.735  --- [ERROR] --- [Dart-CoCo] --- Bad state: No record groups have been started. Use `startRecordGroup` before `record`
pub finished with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:338:7)
<asynchronous suspension>
#2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:239:15)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:722:18)
#4      _rootRunUnary (dart:async/zone.dart:1192:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#11     _rootRun (dart:async/zone.dart:1184:13)
#12     _CustomZone.run (dart:async/zone.dart:1077:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by alexZaicev** [comment]
@sterrenburg thank you submitting the issue, I've resolved the issues in new version `1.0.4+1` :)
